### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by m3ta4a**

### CODE REVIEW

**Comment by aposhiana** [comment]
Do we need to update the `Gemfile.lock` as well?

**Comment by m3ta4a** [comment]
> Do we need to update the `Gemfile.lock` as well?

Probably? I don't know anything about this gem except that its dependencies are blocking upgrades to bigmaven

**Comment by aposhiana** [comment]
I don't think these changes are backwards compatible. When I run bundle install on my machine I get this error:
```
Gem::InstallError: docile requires Ruby version >= 2.5.0.
An error occurred while installing docile (1.4.0), and Bundler cannot continue.
Make sure that `gem install docile -v '1.4.0'` succeeds before bundling.
```

**Comment by m3ta4a** [comment]
> I don't think these changes are backwards compatible. When I run bundle install on my machine I get this error:
> 
> ```
> Gem::InstallError: docile requires Ruby version >= 2.5.0.
> An error occurred while installing docile (1.4.0), and Bundler cannot continue.
> Make sure that `gem install docile -v '1.4.0'` succeeds before bundling.
> ```

Okay so at a minimum we shouldn't merge until we've got ruby 2.5 locked in on prod and everyone's workstations

**Comment by aposhiana** [comment]
> Okay so at a minimum we shouldn't merge until we've got ruby 2.5 locked in on prod and everyone's workstations

Maybe.

Yeah when I change the Gemfile in bigmaven to read from the `'Bump-json_pure-version'` branch I get the following error when bundling:
```
~/workspace/mavenlink (master) $ bundle install
Fetching git@github.com:mavenlink/gutdata.git
Fetching gem metadata from https://rubygems.org/........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies.......
Bundler could not find compatible versions for gem "terminal-table":
  In snapshot (Gemfile.lock):
    terminal-table (= 1.8.0)

  In Gemfile:
    terminal-table

    gutdata was resolved to 0.6.25, which depends on
      terminal-table (~> 3.0.1)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by m3ta4a** [comment]
> > Okay so at a minimum we shouldn't merge until we've got ruby 2.5 locked in on prod and everyone's workstations
> 
> Maybe.
> 
> Yeah when I change the Gemfile in bigmaven to read from the `'Bump-json_pure-version'` branch I get the following error when bundling:
> 
> ```
> ~/workspace/mavenlink (master) $ bundle install
> Fetching git@github.com:mavenlink/gutdata.git
> Fetching gem metadata from https://rubygems.org/........
> Fetching version metadata from https://rubygems.org/...
> Fetching dependency metadata from https://rubygems.org/..
> Resolving dependencies.......
> Bundler could not find compatible versions for gem "terminal-table":
>   In snapshot (Gemfile.lock):
>     terminal-table (= 1.8.0)
> 
>   In Gemfile:
>     terminal-table
> 
>     gutdata was resolved to 0.6.25, which depends on
>       terminal-table (~> 3.0.1)
> 
> Running `bundle update` will rebuild your snapshot from scratch, using only
> the gems in your Gemfile, which may resolve the conflict.
> ```

Yeah, merging this will be quite down the road a bit. These updates are for supporting rails 6 which is necessary to get us to ruby 3, all in the spirit of getting to rails 7. So I'll just convert this to a draft for now and keep those upgrade branches pointed here.

**Comment by diclophis** [comment]
@m3ta4a lets get this setup for mergination, we want to get the redis gem updated from a branch of ruby26 see this PR: https://github.com/mavenlink/mavenlink/pull/29986

**Comment by diclophis** [comment]
related: https://github.com/mavenlink/mavenlink/pull/30182

**Review by wesleymorlock — APPROVED** [review]
Looks like we got this dev QA'd on pentagon's team staging, so this seems good to me.

**Pull request merged**
